fixtures:
  repositories:
    oracle_java:
      repo: 'https://github.com/Adaptavist/puppet-oracle_java.git'
    packages_repo:
      repo: "https://github.com/Adaptavist/puppet-packages_repos.git"
    stdlib:
      repo: "https://github.com/Adaptavist/puppetlabs-stdlib"
    apt:
      repo: "https://github.com/Adaptavist/puppetlabs-apt"
    elasticsearch:
      repo: 'https://github.com/Adaptavist/puppet-elasticsearch'
  symlinks:
    elasticsearch_config: "#{source_dir}"
